import scipy.sparse as sp
import numpy as np
indptr = np.array([0, 2, 3, 6])
indices = np.array([0, 2, 2, 0, 1, 2])
data = np.array([1, 2, 3, 4, 5, 6])
matrix = sp.csr_matrix((data, indices, indptr), shape=(3, 3))
matrix.todense()
print('=============')
print(matrix.shape)
print('=============')
print(matrix)
print('=============')
print(matrix[0])
print(matrix[0].shape)
print('=============')
print(matrix[0][0])
print(matrix[0][0].shape)
print('=============')
print(matrix.todense())
