import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('=========================')
print(a.shape)
print(a)
print('=========================')
print(a[1,1])
print('=========================')
print('a[1:]=')
print(a[1:])
print('=========================')
print('a[:,1]=')
print(a[:,1])
print(a[...,1])
print('------------')
print(a[:,1:])
